-- Create responses table
CREATE TABLE public.skillshub_quiz (
    response_id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    test varchar NOT NULL,
    module varchar NOT NULL,
    username varchar NOT NULL,
    coach_id varchar,
    test_date DATE DEFAULT CURRENT_DATE,
    q1 varchar,
    q2 varchar,
    q3 varchar,
    q4 varchar,
    q5 varchar,
    q6 varchar,
    q7 varchar,
    q8 varchar,
    q9 varchar,
    q10 varchar,
    q11 varchar,
    q12 varchar,
    q13 varchar,
    q14 varchar,
    q15 varchar,
    q16 varchar,
    q17 varchar,
    q18 varchar,
    q19 varchar,
    q20 varchar,
    q21 varchar,
    q22 varchar,
    q23 varchar,
    q24 varchar,
    q25 varchar,
    q26 varchar,
    q27 varchar,
    q28 varchar,
    q29 varchar,
    q30 varchar,
    course varchar NOT NULL,
    user_id uuid,
    sex varchar(1),
    grade varchar(1),
    gender varchar(1),
    FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);

-- Create test configuration table
CREATE TABLE public.skillshub_marks (
    test_id varchar NOT NULL,
    test_name varchar NOT NULL,
    course varchar NOT NULL,
    module varchar NOT NULL,
    testmaxscore integer NOT NULL,
    PRIMARY KEY (test_id, course, module)
);